services:
  - type: web
    name: telegram-file-bot-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TELETHON_SESSION_STRING
        sync: false
      - key: PORT
        value: "10000"
